version: "3.8"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl